### ISSUE TITLE
Table club, status {active, inactive} 

### ISSUE THREAD

**Issue by RaniaOj** [huda46/Assignment7#1]
@huda46 @saile3 
When has a club the status "active"? → when it contains at least one trainer or at least one trainer and one club member ?
and the same for "inactive" → no trainer or no trainer and no club members?

**Comment by saile3** [comment]
The club just has a property as active or inactive to temporarily disable the functioning of the club.  There is no need for this property to be derived from a trainer or a member.  
User case 1: A club was created but it's still not ready to be functioning due to various reasons like certain formalities are yet to be completed. 
User case 2:  A club was newly created but it's still in the beta phase where they want to get feedback from members or check if there would be enough members interested in it.

**Comment by RaniaOj** [comment]
When creating a new club what would be the affected value to the status "active" or "inactive"? and how do we know if the status has changed?

**Comment by saile3** [comment]
while creating a club the status could be set to anything active or inactive. it does not matter.  the status is changed using the edit.
example: an active club realizes that after the registration period. they have not many participants and can make a decision to inactive the club for that semester

**Comment by RaniaOj** [comment]
thank you for the answer!
After discussion with my team member @troppdus we would suggest for: 
- Case 1: add one other state "formalities completed" to check if the club has already all formalities accomplished so that we can know if it is active or inactive
- Case 2: add one other state "beta phase" to check if the club is in beta phase so that we can know if it is active or inactive. 
What do think about?

**Comment by saile3** [comment]
@huda46 and team. what is your thought on it? I was thinking of having 4 options "Active", Inactive", "Complete", and Beta".
Active - it's open for registration.
Inactive - not open for registration/ not functioning. 
Complete- the registration is closed and all participants will be billed.
Beta-registered participants need not pay (be billed) it's free.

**Comment by troppdus** [comment]
Yes this would make more sense. Then we can add some constraints to the states. 
Like:
Members can only join in the club, when it is active or beta-registered
And so on

But then I have a additional question. 
Lets say a club can only happening in summer, then the club would be inactive in winter. Would the member list be empty in winter? Or would be the club deleted after the summer?

**Comment by saile3** [comment]
yes, end of each term the admin will manually edit the club and remove all the participants and make it ready for the new term. if the club is not happening in the winter term it would be in inactive status.

**Comment by RaniaOj** [comment]
thank you!
