### ISSUE TITLE
confirmation of the domain model

### ISSUE THREAD

**Issue by troppdus** [huda46/Assignment7#10]
Are you agree with our approach for the domain model? 
![domain_information_model](https://github.com/huda46/Assignment7/assets/80984875/ae5083b8-4396-42b7-8747-d71855a0720f)

**Comment by huda46** [comment]
from my side I agree about it

**Comment by saile3** [comment]
Looks good. just  wanted to let you know that the Club can have 0 or more members and a member can have zero or more clubs

**Comment by saile3** [comment]
I agree
