### ISSUE TITLE
confirmation of the requirements document

### ISSUE THREAD

**Issue by RaniaOj** [huda46/Assignment7#11]
Can you please check the the requirements document? Did we missed something?

**Comment by huda46** [comment]
Hiiiii, from my side I agree on them thank u.

**Comment by saile3** [comment]
Looks good, I agree just wanted to point out that we had discussed that the fee is added to the member profile only when the associated club status is complete.

**Comment by RaniaOj** [comment]
@saile3 I will change it.
thank you very much to both of you!
