### ISSUE TITLE
Slogan

### ISSUE THREAD

**Issue by RaniaOj** [huda46/Assignment7#16]
Hii everyone,

what should be the slogan for the BTU-WellnessClub please?

**Comment by huda46** [comment]
Sorry for the late reply, I would suggest, "Empower Your Well-being with BTU-WellnessClub!". but please give me some time so that my grp mate also approves it.

**Comment by saile3** [comment]
I am good with the above slogan

**Comment by RaniaOj** [comment]
It seems good.. Thank you!
