### ISSUE TITLE
Table club, chairs

### ISSUE THREAD

**Issue by RaniaOj** [huda46/Assignment7#2]
@saile3 @huda46 
What is chairs in the table club? Is that an enumeration of the noticed club activities: Sports, courses for relaxation and Dancing courses?

**Comment by saile3** [comment]
The chair is the person head of the club. there could be multiple people who run the club, you can consider chairs as admins

**Comment by RaniaOj** [comment]
do they have a special person type or a special role? like one admin can a student or employee or a guest? do we need maybe to add admin in table person as role ?

**Comment by saile3** [comment]
yes, the admins could be a student, employees, or a guest. but there is no need for a property as a role in the person table. we just need the distinction in the club table that says who are the admins, trainers, and participants. The fee is only collected from the participants

**Comment by RaniaOj** [comment]
thank you for the details!
