### ISSUE TITLE
Some question to the fee system.

### ISSUE THREAD

**Issue by troppdus** [huda46/Assignment7#4]
First of all good morning.
I have some question about the fees.

Member sided:
Should Fee-Total really be a property? In my opinion it should be calculated only on display.
In database for example you would just save the birthday of a person not his age. Because the age changes every year and can be calculated.

Club sided:
What type of fees do you have in your mind? 
For example, have employee always to pay 5€ more then a student and have guest always to pay 10€ more then the student.
-> then we could only save the student fee and calculate the other fees.
Or are the distances between the different fees always different?
-> then we would have to save every fee

**Comment by saile3** [comment]
I agree we can go with that approach. where the total fee is not stored but displayed and the fee can be derived from student fees like mentioned above.

**Comment by troppdus** [comment]
Ok, thank you. Let's do it like this. We will talk later, about the specific prizes. For now, we only need the concept.
