### ISSUE TITLE
What is the purpose of term?

### ISSUE THREAD

**Issue by troppdus** [huda46/Assignment7#5]
What is the purpose of term in schedule?
We already have a time period property and I think most clubs would be in multiple terms.

**Comment by saile3** [comment]
It was just for convenience, to have it also displayed in terms, that the students and faculty are familiar with.

**Comment by saile3** [comment]
it has no particular functionality just for the convenience of the members. Hope it helps.   For example, for guarding club we can mention the term spring, summer, and fall. just the easiest way for people to understand.

**Comment by troppdus** [comment]
So to summarize it, this property is an optional and can have multiple entries, like your example (terms = {spring, summer and fall}).  Did I understand it correct?
