### ISSUE TITLE
When does the schedule gets created for a club?

### ISSUE THREAD

**Issue by troppdus** [huda46/Assignment7#7]
In your description of the creation of the schedule, you write “we create a new schedule for each club”, but in the creation process of the club it isn't mentioned. 
I would understand out of the cite that a schedule is mandatory for a club. So when does the schedule gets created? And when did get it added to a club?

**Comment by saile3** [comment]
schedule need not get added to the club it references the club (uni-directional). when a schedule is created we pick a club for which the schedule is being created. so technically there should exist a club for creating the schedule.

**Comment by troppdus** [comment]
Ok; I understand.
